package com.fossil;

import com.fossil.atw.C1900a;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

public final class bgu<R extends atz> extends atw<R> {
    private final Status mStatus;

    public final Integer KJ() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    final Status Ka() {
        return this.mStatus;
    }

    public final R mo1167a(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void mo1168a(C1900a c1900a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void mo1169a(aua<? super R> com_fossil_aua__super_R) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
